### ISSUE TITLE
Export download does not work in Chrome

### ISSUE THREAD

**Issue by joelmdistdata** [tabulapdf/tabula#350] opened 2015-08-07 14:13 UTC
I click the export button and nothing happens. Where is the exported csv suppose to download?

**Comment by boroboris** [comment] 2015-08-07 14:28
I had the same issue. And it doesn't work for other formats (json, tsv ...) either.

**Comment by tommeagher** [comment] 2015-08-07 15:27
I had the same issue. 

I uploaded a PDF of this http://www.bjs.gov/content/pub/pdf/mljsp0013st.pdf
I traced the table I wanted to try to download. 

Everything seemed to be working, and the preview showed me what I expected. When I click "export", it turns into the spinning arrows and then returns to the regular export button, but nothing happens. No download starts or other window opens or anything.

I'm using Tabula 1.0 on Chrome Version 44.0.2403.130 (64-bit) on a MacBook Air running OS X 10.9.5.

If I "copy to clipboard," it does copy the data there, and I can paste it into a text editor or whatever, but the auto-download doesn't seem to be working. Did I do something wrong in the installation or setup or is this a genuine bug? I'm happy to provide more details or screenshots if you need them.

**Comment by abresler** [comment] 2015-08-07 17:07
Try using it in firefox the exports work there as a work around for now.

**Comment by jazzido** [comment] 2015-08-07 17:38
I can confirm that the bug is present in Chrome. As @abresler pointed out, the feature seems to work as expected in Firefox.

We will take care of this in the next bugfix release.

Thanks y'all for reporting!

**Comment by jeremybmerrill** [comment] 2015-08-11 20:30
@mtigas @jazzido What _IS_ the deal with this bug? The download button is just a form submit button.

**Comment by jqnatividad** [comment] 2015-08-11 20:46
FWIW, also does not work on Chrome Canary Version 46.0.2479.0 canary (64-bit) on OS X El Capitan Beta 5 (15A244d).

**Comment by mtigas** [comment] 2015-08-11 21:51
On click (for "extract" or "copy to clipboard"), looks like [`Tabula.DataView`](https://github.com/tabulapdf/tabula/blob/feature/newUI-ruby/webapp/static/js/pdf_view.js#L326) changes the form's action to the one of whichever submit button you pressed — but I guess Chrome cancels the submit when that happens. Or something.

Anyway, triggering a .submit() on it manually after making the action swap seems to work (& also doesn't double-submit in my testing on Firefox). Commit coming soon.

**Comment by mtigas** [comment] 2015-08-11 21:56
Ah, might be due to order of dom events (one "click" event handler disables that button; but maybe on some browsers it triggers before the other event which does the form url stuff). Anyway, that's there now.

**Comment by jeremybmerrill** [comment] 2015-08-11 22:03
Those were basically my competing, untested theories. Thanks for the fix

Jeremy B. Merrill

**Comment by mtigas** [comment] 2015-09-15 03:08
Fixed in version 1.0.1 — https://github.com/tabulapdf/tabula/releases/tag/v1.0.1

**Closed by mtigas** 2015-09-15 03:08 UTC

**Comment by tommeagher** [comment] 2015-09-17 15:10
Awesome. Works great. Thanks, Mike!
