### ISSUE TITLE
error

### ISSUE THREAD

**Issue by scmarcus** [tabulapdf/tabula#234] opened 2015-01-05 16:50 UTC
Internal Server Error at /pdf/c726a69130a152f57c90c2287991914966ad1ad7/data
  
  
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  

  
    Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:8080/pdf/c726a69130a152f57c90c2287991914966ad1ad7/data
      
    
  
  
    (ArgumentError) comparison of Float with Float failed
  

  
    
    You're seeing this error because you use Rack::ShowStatus.

**Comment by jeremybmerrill** [comment] 2015-01-05 16:58
Thanks for the report; this is a dupe of #207

> Thanks for reporting this issue. This is a known issue that's fixed upstream in tabula-extractor; it'll be fixed in the next release of Tabula. Unfortunately, I don't think there's a workaround, but an older version of Tabula (0.95) should work...

**Closed by jeremybmerrill** 2015-01-05 16:58 UTC
