### ISSUE TITLE
Internet Explorer improperly caches /queue/ JSON requests and is generally just trash :(

### ISSUE THREAD

**Issue by comprehenderic** [tabulapdf/tabula#408] opened 2015-09-28 21:28 UTC
Every time I attempt to import a pdf I get the message "DEBUG: resetting rack response due exception" in the command line window, and the upload progress never changes from "waiting to be processed.."

**Comment by jeremybmerrill** [comment] 2015-09-28 21:58
Is your document really big? Sometimes the processing can take a long time to get started...

(The "DEBUG" message usually doesn't mean there was a problem.)

**Comment by comprehenderic** [comment] 2015-09-28 22:03
Its not very big at all, only 7kb.

Sent from my iPhone

On Sep 28, 2015, at 5:59 PM, Jeremy B. Merrill <notifications@github.com<mailto:notifications@github.com>> wrote:


Is your document really big? Sometimes the processing can take a long time to get started...

(The "DEBUG" message usually doesn't mean there was a problem.)

**Comment by jeremybmerrill** [comment] 2015-09-28 22:09
Hmm. If the PDF isn't sensitive, can you send us a link to it? Or upload a
PDF on the Github issue page.

(The thing NOT to do is not to attach it to an email -- I won't get that.)

**Comment by comprehenderic** [comment] 2015-09-29 13:52
Unfortunately the pdf is sensitive. However, I tried to use the software on another machine with another file and got the same results. Is there a specific version of Java I should be using? Tried it with 6 (wouldn’t  run) 7 & 8 (seemed to act the same with those).

**Comment by jeremybmerrill** [comment] 2015-09-29 15:15
Hmm. Java 7 and Java 8 should both work fine. What browser are you using?

One last possibility: Can you try again to upload your document, wait a minute or so, then open the Web Console and copy-paste any error messages to here? In Firefox, go to Tools -> Web Developer -> Web Console; in Chrome, View -> Developer -> Javascript Console.

Thanks and sorry for hte inconvenience.

**Comment by jazzido** [comment] 2015-09-29 15:17
Hi @comprehenderic 

You can email your document privately to us, if possible. Just send it to *manuel at jazzido dot com*

**Comment by comprehenderic** [comment] 2015-09-29 16:10
Aha! It works fine after I tried in Firefox. IE11 seems to be the problem. We have to use IE for some other software, so I’d like the end user to be able to use this in IE. Do I need to use an older version, or set some permissions or something?

**Comment by jeremybmerrill** [comment] 2015-09-29 17:18
No, it's probably our fault. I'll try to check on IE Edge and IE11 next time I get the chance. You'll have to either use Firefox/Chrome/Safari or wait until the next version (which should fix this problem, once we figure out what it is).

**Comment by pthartmann** [comment] 2015-10-15 19:16
Just wanted to provide feedback that I had the same issue with IE11 - though both Chrome & Firefox work wonderfully.

Thank you!

**Comment by jeremybmerrill** [comment] 2015-10-15 20:35
@pthartmann: thank you for the reminder, I forgot.... :)

**Comment by jeremybmerrill** [comment] 2015-10-17 16:54
Okay, the problem is a mundane one. Internet Explorer (including Edge on Win10, which is what I tested with) inappropriately caches the JSON request that the Tabula webpage uses to ask the Tabula server for the status of your document. After a short period of time (seconds, maybe a couple minutes for huge documents), the document is done. If you were to refresh the page, you'd see it in your file library.

*The workaround (for now):* 

1. Switch to Firefox or Chrome.
2. In Internet Explorer, let Tabula "process" your document for five minutes or so, then refresh the page and click on "Extract Data" next to your document in the File Library.

I'll examine why this is happening. Should be an easy fix. Might be as easy as adding a cachebuster querystring argument...

**Comment by jeremybmerrill** [comment] 2015-10-17 17:30
This bug is fixed in https://github.com/tabulapdf/tabula/commit/8f5e24579bb79d94d21836128206a0456db25c18. Thank you both @comprehenderic, @pthartmann for reporting the bug and sorry for the wait on the fix. (For workarounds, see above comment.)

Hey @mtigas: Can we get a new Windows build off of stable/1.0.x? Other platforms should be okay. (I can also send you a built version, just the output of `rake windows` if that's helpful. Lmk.)

**Comment by HenryElder** [comment] 2015-10-28 13:24
It looks like the windows release is still 1.0.1 from 15th September unless there's somewhere else it's listed I haven't found.

**Comment by jeremybmerrill** [comment] 2015-10-28 13:27
That's correct. I need to harass @mtigas to make a new official build. If you're waiting on a fix, you're welcome to use my testing build from here: https://www.dropbox.com/s/302zrspteh5cflu/tabula-win-revf2bb3d14efeb2dcc1f49a0d592f0a90b781e13f4.zip?dl=1

**Comment by Henry-E** [comment] 2015-10-28 14:15
Thanks very much for getting back to me so fast. Unfortunately my version of IE 11 still seems to be having trouble with your testing build but I'm happy to wait for the release.

**Comment by jeremybmerrill** [comment] 2015-10-28 14:48
The same trouble?

**Comment by Henry-E** [comment] 2015-10-28 15:17
Yes, same error message and general not working-ness. I'm going to try and get another browser installed.

**Comment by jeremybmerrill** [comment] 2015-10-28 15:38
Hmm, that's surprising to me. Another browser should work...

If you still want to try IE, have you tried letting it process for a few minutes, then refreshing the page? Your file should be fully processed and show up in your file library...

**Comment by mtigas** [comment] 2015-10-29 03:44
@comprehenderic @pthartmann @Henry-E: I’ve uploaded another Windows build; can you try this? https://cdn.tig.as/dist/tabula/1.0/tabula-win-1.0.1.1-rc1.zip

Will release within the next day or two unless something's completely wrong with it.

**Comment by Henry-E** [comment] 2015-10-29 13:29
It still doesn't appear to be working. The test pdf is only small, 365kb and 3 pages long. I wait, refresh and don't see anything. If there's anything more detailed I can do to help you test please let me know. Thanks for the help.

DEBUG: resetting rack response due exception
io/console not supported; tty will not be manipulated
DEBUG: resetting rack response due exception

**Comment by jeremybmerrill** [comment] 2015-10-29 14:12
Yikes. Lemme re-check tomorrow night on my windows machine, to see if I can
figure out what's going on...

Jeremy B. Merrill

**Comment by jeremybmerrill** [comment] 2015-10-29 14:50
reopening for now;

I wonder if we need to cachebust the tabula.js file that sets the JQuery parameter that prevents caching JSON requests...

**Comment by jeremybmerrill** [comment] 2015-10-30 03:09
Much to my befuddlement and dismay, the new version worked perfectly for me on IE edge on Windows 10. I have one idea that I'll implement soon -- just the cachebuster on tabula.js, and then we'll test that out...

Sorry to make this a multi-attempt ordeal for all of y'all...

**Comment by Henry-E** [comment] 2015-10-30 06:04
I should have mentioned we're still on Windows 7, sorry. That's probably part of the issue.

**Comment by jeremybmerrill** [comment] 2015-10-30 12:47
Did another browser work? (If so, I don't think the OS is the problem.)

**Comment by jeremybmerrill** [comment] 2015-10-30 13:11
Okeedoke, @mtigas, I added a cachebuster to ensure users get the latest tabula.js which includes the fix for IE's dumb caching behavior: 0783fe5

Can you rebuild when you get a chance?

**Comment by mtigas** [comment] 2015-10-30 16:00
Don’t have a Windows box to test on, but:
https://cdn.tig.as/dist/tabula/1.0/tabula-win-1.0.1.1-rc2.zip

Updated my local Java, so it's on Java 8u66 and not whatever I originally built 1.0.1 with (probably u65?). Probably doesn’t matter though.

**Comment by jeremybmerrill** [comment] 2015-11-04 00:46
@comprehenderic @pthartmann @Henry-E: Any chance one of y'all would be willing to test Mike's new build?  https://cdn.tig.as/dist/tabula/1.0/tabula-win-1.0.1.1-rc2.zip

Thanks!

**Comment by Henry-E** [comment] 2015-11-04 08:45
I do hate to disappoint you but it still doesn't appear to work.

**Comment by comprehenderic** [comment] 2015-11-04 15:06
Isn't working for me either. Should mention, that along with IE 11, I'm on Windows 7.

**Comment by jeremybmerrill** [comment] 2015-11-04 16:39
Dammit. I'll try to find a VM and test on Win7... Thank you both, again, for generously testing these intermediate builds.

**Comment by Henry-E** [comment] 2015-12-10 10:41
I'm not sure what changed but the build I downloaded on the 4th November appears to work on IE11 now. It didn't seem to work when I tried it out earlier.

**Comment by Henry-E** [comment] 2015-12-10 11:14
Never mind. The PDF was only there because I uploaded it in another browser. Still can't upload files. The extract of cells and stuff works perfectly.

**Comment by jeremybmerrill** [comment] 2015-12-10 15:58
Hmm. I still haven't had a chance to test on a VM (i.e. I forgot...), so I'll try to get to this soon.

**Comment by jeremybmerrill** [comment] 2015-12-19 22:48
Okay. Thank you for your patience... 

Can those of you on IE11 try out this build? https://www.dropbox.com/s/npvrzlx4lz0tn42/tabula-win.zip?dl=0

I was able to replicate the issue in a modern.ie VM and it looks like the bug is that IE is... a piece of software of questionable quality. In some cases, IE11 incorrectly serializes multipart form-data, which confuses Rack (a Tabula component). The solution is to add a "fake" form element at the end of the form, as I've done here: https://github.com/tabulapdf/tabula/commit/4d45f8961d33c2ad073d094d7fb5936f76b1d4b8#diff-993d50876f35e232013fe86cdcef31f2R269

This fixed the issue for me. If this works for you too, we'll merge this into master and rebuild.

**Comment by Henry-E** [comment] 2015-12-21 09:33
Congratulations this appears to fix the issue in IE11

**Comment by jeremybmerrill** [comment] 2015-12-21 15:50
Hooray!

**Closed by jeremybmerrill** 2015-12-21 15:50 UTC

**Comment by jeremybmerrill** [comment] 2015-12-21 15:56
Oh, @mtigas, when you get a chance, could you rebuild Windows?
