### ISSUE TITLE
Problems converting http://ww1.microchip.com/downloads/en/DeviceDoc/60001320C.pdf

### ISSUE THREAD

**Issue by JimNickerson** [tabulapdf/tabula#520] opened 2016-07-02 16:13 UTC
tabula windows 10 edge and chrome and firefox say "Sorry, your file upload could not be processed. Please double-check that the file you uploaded is a valid PDF file and try again"
Open with IE hangs on "waiting to be processed"
[http://ww1.microchip.com/downloads/en/DeviceDoc/60001320C.pdf](url)

**Comment by jeremybmerrill** [comment] 2016-07-04 15:23
Hi @JimNickerson: Looks like this is a bug we're seeing a couple reports of lately; out of the 700+ pages in the PDF, there's likely one or two that Tabula is choking on. My recommendation is to use a tool like `pdftk` to extract just the pages with the tables you're interested in, then upload those to Tabula.

Stacktrace indicates this is a dupe of #513; closing so discussion of the JPedal issue is at that issue. Feel free to continue the discussion here regarding your workaround.
```java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
  at java.util.concurrent.FutureTask.report(java/util/concurrent/FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(java/util/concurrent/FutureTask.java:192)
  at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
  at RUBY.afterExecute(/home/my_username/code/tabula/lib/tabula_job_executor/executor.rb:42)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1150)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(java/lang/Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException
  at java.lang.System.arraycopy(Native Method)
  at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
  at RUBY.initialize(/home/my_username/code/tabula/lib/thumbnail_generator.rb:56)
  at RUBY.perform(/home/my_username/code/tabula/lib/tabula_job_executor/jobs/generate_thumbnails.rb:15)
  at RUBY.call(/home/my_username/code/tabula/lib/tabula_job_executor/executor.rb:104)
  at GenerateThumbnailJob_1233439965.call(GenerateThumbnailJob_1233439965.gen:13)
  at java.util.concurrent.FutureTask.run(java/util/concurrent/FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1142)
  ... 2 more
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
  at java.util.concurrent.FutureTask.report(java/util/concurrent/FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(java/util/concurrent/FutureTask.java:192)
  at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
  at RUBY.afterExecute(/home/my_username/code/tabula/lib/tabula_job_executor/executor.rb:42)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1150)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(java/lang/Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException
  at java.lang.System.arraycopy(Native Method)
  at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
  at RUBY.initialize(/home/my_username/code/tabula/lib/thumbnail_generator.rb:56)
  at RUBY.perform(/home/my_username/code/tabula/lib/tabula_job_executor/jobs/generate_thumbnails.rb:15)
  at RUBY.call(/home/my_username/code/tabula/lib/tabula_job_executor/executor.rb:104)
  at GenerateThumbnailJob_1233439965.call(GenerateThumbnailJob_1233439965.gen:13)
  at java.util.concurrent.FutureTask.run(java/util/concurrent/FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1142)
  ... 2 more
```

**Closed by jeremybmerrill** 2016-07-04 15:23 UTC

**Comment by JimNickerson** [comment] 2016-07-04 15:35
I am wondering if it is indeed a java exception might it be possible to
catch the exception and skip to the next table ?
Jim

**Comment by jeremybmerrill** [comment] 2016-07-04 15:55
The problem is in generating thumbnails for the GUI; for some reason, JPedal (the PDF drawing library) is failing when trying to open PDFs. So there's really no opportunity to catch the error. 

You could certainly try the command-line tool (which doesn't depend on thumbnails, since there's no GUI): https://github.com/tabulapdf/tabula-java/
