### ISSUE TITLE
Tabula version 1.1.0 always exports with lattice method

### ISSUE THREAD

**Issue by overvolting** [tabulapdf/tabula#607] opened 2017-01-06 19:04 UTC
Hello,

I've tried tabula version 1.1.0 with a single pdf table. When the lattice method is selected (default) the preview of the table is wrong. When the selection of method is changed to 'stream' the preview of the table is correct, however every time the table is exported to .csv file, the lattice method is applied, even if the stream method is selected.

The work around has been to select the preview html generated while 'stream' method is selected and copy/paste into excel.

**Comment by jeremybmerrill** [comment] 2017-01-07 17:14
Hi @overvolting, you're exactly right about what the problem is. It's [fixed on the master branch](https://github.com/tabulapdf/tabula/commit/c155d6045f20906d819049c00fc976e81596de49), but that fix hasn't made it into the latest release yet. If you want, you can build Tabula from master as an alternative workaround.

**Closed by jeremybmerrill** 2017-01-07 17:14 UTC
