### ISSUE TITLE
Set Extraction Type when one selection returns 2+ tables

### ISSUE THREAD

**Issue by wcraft** [tabulapdf/tabula#497] opened 2016-04-28 16:46 UTC
Hi, when I click 'preview and extract data', tabula brings me to the normal 'extract data' page. I can see the data normally for a brief moment, but then the table disappears. When I export as a csv, it exports normally.

**Comment by jeremybmerrill** [comment] 2016-05-18 15:10
Can you send us the PDF you used that caused this issue? And what browser are you using?

**Comment by wcraft** [comment] 2016-05-18 16:12
Hi, the issue was occurring on Firefox 46.0.1. It was happening on a number of different PDFs downloaded from https://dps.mn.gov/divisions/bca/bca-divisions/mnjis/Pages/uniform-crime-reports.aspx 

I was working with the Unified Crime Reports at the bottom of the page, and the error occurred on at least 3 different pdfs.

**Comment by jeremybmerrill** [comment] 2016-05-19 13:38
aha! it's a bug, nice find!

the issue is [here](https://github.com/tabulapdf/tabula/blob/master/webapp/static/js/pdf_view.js#L299-L307) -- sometimes in lattice mode, multiple tables are returned for a single selection. since we're zipping a one-length array with a (N>1)-length array, 3 in this case, coord_set is undefined, hence the error.

Will get to fixing this soon, @wcraft. Thanks for the report.

**Comment by wcraft** [comment] 2016-05-19 14:55
Awesome! Thanks for the amazing program

**Comment by jeremybmerrill** [comment] 2016-08-20 17:07
> Will get to fixing this soon

This was a lie... :D but it's fixed now, in master.

**Closed** 2016-08-20 17:07 UTC
