### ISSUE TITLE
What is in preview is not in JSON

### ISSUE THREAD

**Issue by cgood92** [tabulapdf/tabula#569] opened 2016-10-18 16:37 UTC
I uploaded a PDF, and extracted every page.  When I first the button " Preview & Export Extracted Data", I scan the preview and I notice that there are a few missing pages that for some reason aren't in the preview, but were in the PDF.  

Well, I try changing the preview some.  I click on "STREAM", and in the preview I see the missing pages (as in the image below).  I'm excited about that.  So, I export that, and in all the export files/versions, those pages are still missing, even though they were in the preview.  

I click on "LATTICE", and the pages are missing.  So, they only show up in STREAM, but then I can't get those pages to show up in the download.

I love this tool, and it could possibly solve a huge problem of mine.  So, I'm willing to help make this work.

<img width="1416" alt="export_data___tabula" src="https://cloud.githubusercontent.com/assets/5473697/19487099/759e4696-951e-11e6-88c0-ac922b3d670b.png">

**Comment by jeremybmerrill** [comment] 2016-11-18 22:48
Are you able to share with me the PDF? Upload via the Github interface, email or a web-accessible link all work. I'd like to check this out...

**Comment by cgood92** [comment] 2016-11-19 04:15
[2-William-Carey-Opening-Statement.pdf](https://github.com/tabulapdf/tabula/files/601254/2-William-Carey-Opening-Statement.pdf)

**Comment by jeremybmerrill** [comment] 2016-11-19 19:17
First, a solution to your particular problem: for each page that you notice is missing in the results, find it in the selection view and expand the selection slightly. (The problem is that some of the bounding lines of the table on that page are *just slightly* outside the selection, which throws off the extraction algorithm.)

Second, why did the download not match the preview? I don't know yet. :) But I'm going to figure it out.

Just to make sure I understand what steps you took that led to this bug -- you made some selections, clicked the Stream button, then clicked download? And was the problem just in the downloaded JSON, or did you notice it in the downloaded CSV too?

**Comment by jeremybmerrill** [comment] 2016-11-19 19:32
Ah, okay, never mind. I was able to replicate.

1. Open the PDF in Tabula.
2. Click autodetect.
3. Click stream. (and observe that the "They knew" line is visible in the preview.)
4. Click download CSV. 
5. observe that the "they knew" line is not present in the CSV. (or likewise for the data JSON)

**Comment by jeremybmerrill** [comment] 2016-11-19 21:06
fixed in https://github.com/tabulapdf/tabula/commit/c155d6045f20906d819049c00fc976e81596de49. @cgood92 -- if my suggestion above doesn't work, I'd be happy to build you a custom version of Tabula with the above commit included for your platform (Win/Mac/Jar).

**Closed by jeremybmerrill** 2016-11-19 21:06 UTC

**Comment by cgood92** [comment] 2016-11-21 15:44
Thank you @jeremybmerrill for your help!  I have cloned this repo, and tried to go through the steps to build this locally.  My problem is that `bundle install` is producing these errors:

```
~/development/cgood92-STASH/tabula$ > sudo bundle install
Gem::GemNotFoundException: can't find gem bundler (>= 0.a)
  find_spec_for_exe at /Users/cgood92/.rvm/rubies/jruby-9.1.5.0/lib/ruby/stdlib/rubygems.rb:271
  activate_bin_path at /Users/cgood92/.rvm/rubies/jruby-9.1.5.0/lib/ruby/stdlib/rubygems.rb:298
             <eval> at /Users/cgood92/.rvm/gems/jruby-9.1.5.0/bin/bundle:22
               eval at org/jruby/RubyKernel.java:995
             <main> at /Users/cgood92/.rvm/gems/jruby-9.1.5.0/bin/jruby_executable_hooks:15
```

Any ideas?  I have done the rest of the steps...

Once I can get this running, I will be so grateful for your fix.  Because I have a project involving several thousand pages of analyzing data, which was going to have to be done by hand, unless I can get Tabula to do all the heavy lifting for me!

**Comment by jeremybmerrill** [comment] 2016-11-21 15:53
Oops, those instructions are kind of old. Lemme update 'em real quick. 

Did you already run `gem install bundler`? (And you may want to run `bundle install` as the ordinary user, not sudo. Alternatively, you could install bundler with sudo, which would may fix the issue in your comment.)

**Comment by cgood92** [comment] 2016-11-21 15:58
I feel like I just repeated the same steps as I've done the past 5 times of trying, but for some reason this time it worked.  Maybe it was the `sudo gem install bundler`, not sure.

Regardless, I have the project running locally now.  It will take some testing to see if your fix has corrected what I was struggling with, but I have great hopes that it will.  Thank you again @jeremybmerrill!

**Comment by jeremybmerrill** [comment] 2016-11-21 16:00
Awesome, great. Glad to hear you've got it running. Lemme know how it goes

**Comment by cgood92** [comment] 2016-11-21 20:59
@jeremybmerrill This is working.  A few issues, but that's ok.  So I've built a .jar off of the latest source code, and now I'd like to run it via CLI, such as doing `java -jar ./build/tabula.jar --help` or specify pages and such.  But, I can't seem to get that to work... what am I missing?  I'm really trying to use terminal to automate some of this, as there are a lot of PDF's and such.  And, I just want to set the page area to full page anyway.  

I've been trying to look at https://github.com/tabulapdf/tabula-java, but not having success...

**Comment by jeremybmerrill** [comment] 2016-11-21 21:23
The jar you've built here is the web UI. You should be able to run it with `java -jar ./build/tabula.jar` and then visit `localhost:8080` to interact with the UI as you would with the downloaded, mac-packaged one. (The Mac package is just a thin, signed wrapper for the jar). But since the one you built has the UI fix, hopefully you should be able to extract the data correctly after clicking the Stream button.

The command line version of Tabula you'd download from here: https://github.com/tabulapdf/tabula-java/releases/download/tabula-0.9.1/tabula-0.9.1-jar-with-dependencies.jar No need to build it yourself, although you can if you want. This has a help command, etc. and is built to support automating your table extraction. (There are also Ruby, Python, R and Node bindings, if that's more to your preference than Java)
