### ISSUE TITLE
Text qualifier "" is only included in exported (tsv) format if table text contains control characters (e.g. \n)?

### ISSUE THREAD

**Issue by haematologic** [tabulapdf/tabula#357] opened 2015-08-08 20:48 UTC
The problem is that some fields have text qualifiers *i.e* ```""``` and others don't. 
This is the problematic Tabula output in TSV format http://pastebin.com/sWS08XE1

This is annoying for removing \n from within fields (as apposed to \n relating to new row) when cleaning data with regex &ndash; *i.e.* the first field in each row may or may not be quoted.

This is desired:
```
"field1"\t"field2"
```
However this is the output seen for some fields:
```
 field1\t"field2"
```

The raw data is the 'H1' table from page 25 of this file http://www.jrcptb.org.uk/sites/default/files/2010%20Haematology%20%28amendment%202012%29.pdf

**Managed workaround with regex**
I know each (genuine) row has an empty field which is qualified "" at the end hence the first regex negative lookbehind selector.
```
FIND: (?<!"")\n```
REPLACE: (blank)
```
I add quotes around any word blocks at the beginning of each line that do not already begin with "
```
FIND: ^(?!")((\w+\s)+)
REPLACE: "$1"\t
```
This is the desired output fully text qualified tsv http://pastebin.com/hdNXdwa7

**Comment by jeremybmerrill** [comment] 2015-08-11 13:15
Hi @haematologic:

You're certainly right that the CSV (or in this case, TSV) format is ill-defined. We use the Ruby CSV gem which [does not quote all fields by default](http://ruby-doc.org/stdlib-2.0.0/libdoc/csv/rdoc/CSV.html#DEFAULT_OPTIONS). As you correctly noticed, it only quotes fields with characters that are used as delimiters ("\t" in TSV, "," in CSV, etc., along with newlines and carriage returns for those dialects).

Thanks for reporting your desired behavior. As you might expect, there are other circumstances in which unquoted *SVs are desired, so my guess is that we'll remain with the current default output option, but we're always glad to hear user feedback. I'm closing the issue, since this is expected behavior, but feel free to continue to discuss (you or others).

**Closed by jeremybmerrill** 2015-08-11 13:15 UTC
